const car = [
  {
    id: 1,
    owner: 1221,
    createdOn: new Date(),
    state: 'New',
    status: 'available',
    price: 112111.0,
    manufacturer: 'Tesla',
    model: 'Model 3',
    bodyType: 'car',
  },
  {
    id: 2,
    owner: 1222,
    createdOn: new Date(),
    state: 'New',
    status: 'available',
    price: 22311123,
    manufacturer: 'Nissan',
    model: 'Leaf',
    bodyType: 'car',
  },
  {
    id: 3,
    owner: 1223,
    createdOn: new Date(),
    state: 'Used',
    status: 'available',
    price: 100222.23,
    manufacturer: 'Tesla',
    model: 'X',
    bodyType: 'truck',
  },
  {
    id: 4,
    owner: 1224,
    createdOn: new Date(),
    state: 'Used',
    status: 'available',
    price: 122810.0,
    manufacturer: 'Lucid',
    model: 'Air',
    bodyType: 'car',
  },
];

export default car;
